#ifndef _RM_LIB_CONF_H_
#define _RM_LIB_CONF_H_
#endif

/* DSP库添加方法，添加..\Drivers\CMSIS\Lib\ARM\arm_cortexM4lf_math.lib
 * 添加全局宏定义 ARM_MATH_CM4 __TARGET_FPU_VFP
 * 添加引用路径 ..\Drivers\CMSIS\DSP\Include
 * */

#define __USE_RTOS

#define RMLIB_CHASSIS_MODULE_ENABLED
#define RMLIB_KALMANII_MODULE_ENABLED
#define RMLIB_KALMAN_MODULE_ENABLED
#define RMLIB_MOTOR_MODULE_ENABLED
#define RMLIB_PID_MODULE_ENABLED
#define RMLIB_RAMP_MODULE_ENABLED
#define RMLIB_REMOTE_MODULE_ENABLED
#define RMLIB_CANDRIVE_MODULE_ENABLED
#define RMLIB_WATCHDOG_MODULE_ENABLED

#ifdef RMLIB_WATCHDOG_MODULE_ENABLED
	#define CAN2_SUPPORT
#endif

#ifdef RMLIB_WATCHDOG_MODULE_ENABLED
	#define WatchDogENABLE
    #define WatchDoglength 10
#endif

#endif
